done: historypage, likevideopage, watchlaterpage
Adarsh-Patel-Dev/Planet-Player pull request #5
Opened 2022-05-13 08:08 UTC by Adarsh-Patel-Dev

Files to check:
 - Context folder
 -Pages
    -LikedVideoPage
    -HistoryPage
    -Watchlaterpage
    -SinglevideoCard
    
  Files to ignore:
    PlaylistCard
    PlaylistPage

2022-05-13 11:02 UTC, Naman-Saxena1 requested changes
Code looks fine and functionality is also working in preview.
After adding to watch later, there should be some toast/alert to notify it has been added, I clicked 2-3 times thinking it was not added.
Also, after adding video to playlist, you should close the modal.

2022-05-13 17:00 UTC, iprankurpandey approved these changes

2022-05-16 15:26 UTC, Naman-Saxena1 approved these changes
Functionality is working fine, I suggest you add functionality of add to playlist by clicking on playlist label.
Also add cursor: pointer on create button

![Capture3](https://user-images.githubusercontent.com/90456667/168628161-1aa4449f-5bfa-452c-9899-4a32a90c6133.PNG)

2022-05-16 16:48 UTC, SinchanaMS approved these changes
The UI looks good.  Also liked how separate playlist toasts are shown for the creation of playlists and on video being added to them. Good work!

I found some repetitive properties in css files, especially gap. Please check.
Remove logs and unused commented code for better readability of code.

2022-05-16 16:48 UTC, SinchanaMS commented on src/App.css
> +  gap: 8px;
Use variables for the colors.
gap property is repeated thrice. Please check.

2022-05-16 16:48 UTC, SinchanaMS commented on src/App.js
> +import { SinglePlaylistPage } from "./pages/SinglePlaylistPage/SinglePlaylistPage";
You can make use of barrels (a common index file) to import these files to make the code concise.

2022-05-16 16:48 UTC, SinchanaMS commented on src/components/Card/PlaylistCard/PlaylistCard.jsx
> +//   const { addToWatchLater, setWatchLater } = useWatchLaterContext();
Remove logs and unused commented code.

2022-05-16 16:48 UTC, SinchanaMS commented on src/components/Card/SinglevideoCard/singlevideo.css
>      gap: 0rem;
gap is repeated here as well.

2022-05-16 21:01 UTC, Adarsh-Patel-Dev commented
Added toast Alerts, playlist functionality

2022-05-16 21:02 UTC, merged